name: elshamistore
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.6
  file_picker: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  fonts: 
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Bold.ttf
          weight: 700
        - asset: fonts/Rubik-Italic.ttf
          style: italic
  uses-material-design: true

